import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import MyInfo from "./components/MyInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="ko">
         <body className="bg-[#111111]">
            <Navbar />
            <MyInfo />
            {children}
         </body>
      </html>
   );
}
